services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /cloud/Docker/gluetun/config:/gluetun
    environment:
      - TZ=Asia/Kolkata
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=openvpn
      - OPENVPN_CUSTOM_CONFIG=/gluetun/custom.conf
      - OPENVPN_USER=${MY_OPENVPN_USER_FROM_ENV_FILE}
      - OPENVPN_PASSWORD=${MY_OPENVPN_PASSWORD_FROM_ENV_FILE}